SELECT NOW();

CREATE TABLE tbl_todo(
	tno INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	dueDate DATE NOT NULL,
	writer VARCHAR(50) NOT NULL,
	finished TINYINT DEFAULT 0
);

SELECT * FROM tbl_todo;

SELECT * FROM board;
